program: src/policy_eval.py
name: policy_ground_truth
project: policy_eval
description: calculate ground truth value for policies
method: grid
parameters:
  env_id:
    values: ["MultiBandit"]
  seed:
    min: 1
    max: 10
  policy:
    values: [0,20,40,60,80]
  num_episodes:
    value: 100000
  sampler: 
    value: "GroundTruth"
  repeats:
    value: 1

