program: src/policy_eval.py
name: MultiBandit
project: policy_eval
description: calculate policy value using various methods
method: grid
parameters:
  env_id:
    values: ["MultiBandit"]
  seed:
    min: 1
    max: 10
  policy:
    values: [0,20,40,60,80]
  num_episodes:
    value: 10000
  repeats:
    value: 30
  sampler: 
    values: ["BPS_100_1e-2", "MonteCarlo", "ROS_1e4"]

