program: src/policy_gen.py
name: policy_gen
project: policy_eval
description: generate policies of differing strengths
method: grid
parameters:
  env_id:
    value: "MultiBandit"
  seed:
    min: 0
    max: 10
  policy:
    value: "REINFORCE"
  model:
    value: "TabularNN"
  train_steps:
    value: 100 
  n_policies:
    value: 5